# Add default properties here
spring:
  application.name: vocabulary-rest-ws
  jackson.default-property-inclusion: NON_EMPTY

management:
  server.port: 8081
  endpoints.web.exposure.include: "*"
  endpoint.shutdown.enabled: true

security:
  actuatorSecret: stop

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: rgz522
    password:

security:
  loginApiBasePath: http://api.gbif-dev.org/v1

