TRUNCATE TABLE concept_tag CASCADE;
TRUNCATE TABLE tag CASCADE;
TRUNCATE TABLE concept_definition CASCADE;
TRUNCATE TABLE concept_label CASCADE;
TRUNCATE TABLE concept_alternative_label CASCADE;
TRUNCATE TABLE concept_hidden_label CASCADE;
TRUNCATE TABLE concept RESTART IDENTITY CASCADE;