# Add default properties here
spring:
  application.name: vocabulary-ws

management:
  server.port: 8081
  endpoints.web.exposure.include: "*"
  endpoint.shutdown.enabled: true

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: rgz522
    password:

security:
  loginApiBasePath: http://api.gbif-dev.org/v1

