spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: rgz522
    password:

// TODO: remove, it's just to test it with the registry in local
server.port: 8090

security:
  loginApiBasePath: http://localhost:8080

