# Add default properties here
spring:
  application.name: vocabulary-ws

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: rgz522
    password:

security:
  loginApiBasePath: api.gbif-dev.org/v1

